<a href="https://colab.research.google.com/github/Priyanka797/Exploratory-Data-Analysis-EDA-/blob/main/Multiple_Linear_Regression_Project.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [6]:
#importing libraries
import numpy as np
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression
from sklearn.metrics import mean_squared_error
import matplotlib.pyplot as plt

In [7]:
# loading dataset
df= pd.read_csv('https://raw.githubusercontent.com/Priyanka797/car-price-prediction-linear-regression/refs/heads/main/CarPrice_Assignment.csv')

In [8]:
# Explore dataset
df.head()
df.tail()
df.info()
df.describe()
df.shape
df.size
df.max
df.min

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 205 entries, 0 to 204
Data columns (total 26 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   car_ID            205 non-null    int64
 1   symboling         205 non-null    int64
 2   CarName           205 non-null    object
 3   fueltype          205 non-null    object
 4   aspiration        205 non-null    object
 5   doornumber        205 non-null    object
 6   carbody           205 non-null    object
 7   drivewheel        205 non-null    object
 8   enginelocation    205 non-null    object
 9   wheelbase         205 non-null    float64
 10  carlength         205 non-null    float64
 11  carwidth          205 non-null    float64
 12  carheight         205 non-null    float64
 13  curbweight        205 non-null    int64
 14  enginetype        205 non-null    object
 15  cylindernumber    205 non-null    object
 16  enginesize        205 non-null    int64
 17  fuelsystem        205 non-null    object
 18  boreratio         205 non-null    float64
 19  stroke            205 non-null    float64
 20  compressionratio  205 non-null    float64
 21  horsepower        205 non-null    int64
 22  peakrpm           205 non-null    int64
 23  citympg           205 non-null    int64
 24  highwaympg        205 non-null    int64
 25  price             205 non-null    float64
dtypes: float64(8), int64(8), object(10)
memory usage: 41.8+ KB

<bound method DataFrame.min of      car_ID  symboling                   CarName fueltype aspiration  \
0         1          3        alfa-romero giulia      gas        std
1         2          3       alfa-romero stelvio      gas        std
2         3          1  alfa-romero Quadrifoglio      gas        std
3         4          2               audi 100 ls      gas        std
4         5          2                audi 100ls      gas        std
..      ...        ...                       ...      ...        ...
200     201         -1           volvo 145e (sw)      gas        std
201     202         -1               volvo 144ea      gas      turbo
202     203         -1               volvo 244dl      gas        std
203     204         -1                 volvo 246   diesel      turbo
204     205         -1               volvo 264gl      gas      turbo

    doornumber      carbody drivewheel enginelocation  wheelbase  ...  \
0          two  convertible        rwd          front       88.6  ...
1          two  convertible        rwd          front       88.6  ...
2          two    hatchback        rwd          front       94.5  ...
3         four        sedan        fwd          front       99.8  ...
4         four        sedan        4wd          front       99.4  ...
..         ...          ...        ...            ...        ...  ...
200       four        sedan        rwd          front      109.1  ...
201       four        sedan        rwd          front      109.1  ...
202       four        sedan        rwd          front      109.1  ...
203       four        sedan        rwd          front      109.1  ...
204       four        sedan        rwd          front      109.1  ...

     enginesize  fuelsystem  boreratio  stroke compressionratio horsepower  \
0           130        mpfi       3.47    2.68              9.0        111
1           130        mpfi       3.47    2.68              9.0        111
2           152        mpfi       2.68    3.47              9.0        154
3           109        mpfi       3.19    3.40             10.0        102
4           136        mpfi       3.19    3.40              8.0        115
..          ...         ...        ...     ...              ...        ...
200         141        mpfi       3.78    3.15              9.5        114
201         141        mpfi       3.78    3.15              8.7        160
202         173        mpfi       3.58    2.87              8.8        134
203         145         idi       3.01    3.40             23.0        106
204         141        mpfi       3.78    3.15              9.5        114

     peakrpm citympg  highwaympg    price
0       5000      21          27  13495.0
1       5000      21          27  16500.0
2       5000      19          26  16500.0
3       5500      24          30  13950.0
4       5500      18          22  17450.0
..       ...     ...         ...      ...
200     5400      23          28  16845.0
201     5300      19          25  19045.0
202     5500      18          23  21485.0
203     4800      26          27  22470.0
204     5400      19          25  22625.0

[205 rows x 26 columns]>

In [9]:
# Handling missing values
df.isnull().sum()

car_ID              0
symboling           0
CarName             0
fueltype            0
aspiration          0
doornumber          0
carbody             0
drivewheel          0
enginelocation      0
wheelbase           0
carlength           0
carwidth            0
carheight           0
curbweight          0
enginetype          0
cylindernumber      0
enginesize          0
fuelsystem          0
boreratio           0
stroke              0
compressionratio    0
horsepower          0
peakrpm             0
citympg             0
highwaympg          0
price               0
dtype: int64

In [10]:
#Handling duplicate value
print(f"The duplicate: {df.duplicated().sum()}")

The duplicate: 0

In [11]:
# dropping th User ID column
data_new = df.drop(['CarName','carbody', 'enginetype','cylindernumber', 'fuelsystem','drivewheel' ] , axis=1)
data_new.head()

,car_ID,symboling,fueltype,aspiration,doornumber,enginelocation,wheelbase,carlength,carwidth,carheight,curbweight,enginesize,boreratio,stroke,compressionratio,horsepower,peakrpm,citympg,highwaympg,price
0,1,3,gas,std,two,front,88.6,168.8,64.1,48.8,2548,130,3.47,2.68,9.0,111,5000,21,27,13495.0
1,2,3,gas,std,two,front,88.6,168.8,64.1,48.8,2548,130,3.47,2.68,9.0,111,5000,21,27,16500.0
2,3,1,gas,std,two,front,94.5,171.2,65.5,52.4,2823,152,2.68,3.47,9.0,154,5000,19,26,16500.0
3,4,2,gas,std,four,front,99.8,176.6,66.2,54.3,2337,109,3.19,3.40,10.0,102,5500,24,30,13950.0
4,5,2,gas,std,four,front,99.4,176.6,66.4,54.3,2824,136,3.19,3.40,8.0,115,5500,18,22,17450.0

In [12]:
#one hot encoding
categorical_cols = ['fueltype', 'aspiration', 'doornumber','enginelocation']

data_new_encoded = pd.get_dummies(data_new, columns=categorical_cols, drop_first=True)

In [13]:
X = data_new[['car_ID', 'symboling', 'wheelbase', 'carlength',
        'carwidth', 'carheight', 'curbweight',
        'enginesize', 'boreratio', 'stroke', 'compressionratio',
        'horsepower', 'peakrpm', 'citympg', 'highwaympg']]

y = data_new['price']

In [14]:
#initialize model
# Split the data into training and testing sets
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3)

# Create and train the linear regression model
model = LinearRegression()
model.fit(X_train, y_train)

LinearRegression()

In [15]:
# Make predictions
y_pred = model.predict(X_test)
print(y_pred)
print(y_test)

[15789.25200573  9638.76151359  6885.5865779  16003.37547934
 16884.58194186 10462.79628789 23770.56074942  6225.92283799
  8414.74164457 14866.35618243  7039.35249368  5408.16904987
 11124.03224167  9425.94227041 13243.22331689 10445.70160394
 11809.45037893 10885.92503806 13976.1563736  10369.52143864
  6118.97485263 10368.30365072  7335.24169022  8173.20121377
 15985.64765118 10664.46184498 23085.80615205 14059.62617293
 14492.71506818  9522.99417097 12673.68123469 24243.95284001
 11434.72410493  7063.41212621  6591.62641463 19716.4360125
  5638.35700468 17687.68980045  6229.08874018  9343.56901654
  7657.53025849 19766.34847274  7491.11396865 15092.53878709
 17558.61073415  5508.82170216 11143.21490515 13548.60540238
 30096.88595784 16745.3576894  28493.35654646  7022.1423884
  7860.70064345 30350.44923373  6640.9166491  28507.81335038
  9500.58494179 22222.02357578 15424.65333904  7958.30536844
  7026.21018167  7060.65882486]
10     16430.0
174    10698.0
44      8916.5
13     21105.0
4      17450.0
        ...
104    17199.0
132    11850.0
192    13845.0
24      6229.0
92      6849.0
Name: price, Length: 62, dtype: float64

In [16]:
print(model.coef_)
print(model.intercept_)

[-1.44568039e+01  3.98146635e+02  1.89084905e+01 -4.15958402e+01
  6.10044006e+02  3.87274921e+02  5.85175129e-01  1.13209709e+02
  1.61396730e+03 -3.59032233e+03  2.78697327e+02  3.28475920e+01
  3.06388243e+00 -1.90115540e+02  1.39496472e+02]
-72404.81859176942